### PR TITLE
S1.19.scousepy

### PR DESCRIPTION
**Pull request by aschmiedeke**
Refitting completed. #20 

Spectra look mostly ok.

For some spectra the baseline deviates from zero and for some there are baseline ripples (35-40,42-46,78,79, 104, 105,109)
One spectrum has a negative dip next to the emission line (63)
For two spectra the baseline is significantly off (107, 108)

### CODE REVIEW

**Comment by aschmiedeke** [comment]
Hey Dan, 
your suggestions and solutions look all good to me. Thank you for catching the sneaky negatives and the broad components. The only thing I noticed is spectrum 145. When I look at it, it now looks like this: 

Screenshot 2022-10-11 at 07 31 31

Maybe this is only my scousepy? In any case it's something we might want to look into just to make sure it's alright.

**Comment by jdhenshaw** [comment]
> Hey Dan, your suggestions and solutions look all good to me. Thank you for catching the sneaky negatives and the broad components. The only thing I noticed is spectrum 145. When I look at it, it now looks like this:
> 
> Screenshot 2022-10-11 at 07 31 31
> 
> Maybe this is only my scousepy? In any case it's something we might want to look into just to make sure it's alright.

This could be your scousepy - particularly if there is a zero-component fit - or a fit that has been removed. I have updated scouse to fix this though, and more recently than when we were working on stuff together so I think this is probably not the case here but it is difficult to tell... @d-l-walker do you remember seeing this?

**Comment by aschmiedeke** [comment]
Thanks Jonny! I have updated my scousepy from 2.1.3.dev1+gcd0a705 to 2.1.3.dev11+g90f053a and that fixed the issue with spectrum 145.

Screenshot 2022-10-11 at 08 01 43

 Everything looks good to me now. I think we can proceed with merging.

**Comment by d-l-walker** [comment]
Hi both -- I was just in the process of responding, then saw @aschmiedeke's new comment. Glad to hear it was just a version issue!

**Review by d-l-walker — APPROVED** [review]
Review of #85 complete.

**Pull request merged**
