### PR TITLE
S1.9.scousepy

### PR DESCRIPTION
**Pull request by aschmiedeke**
Refitting completed. #10 

Spectra look mostly good.

Some spectra with negatives on either side of strong emission peaks (91,92,151,152)
Dip (absorption feature?) at ~ 110-120 km/s for a number of spectra (12-14, 70-73, 82,83, 129-132; example screenshots below).
Two spectra showed wiggles in the baseline (145, 146; example screenshot below).

### CODE REVIEW

**Review by mgsantamaria — COMMENTED** [review]
Beginning review process
I solved the conflict, and merged.

**Comment by mgsantamaria** [comment]
[](https://github.com/mgsantamaria/WP2_pilot-1/blob/main/HC3N_TP_7m_12m_feather/stage_2/s2.9.scousepy)

I'm trying to figure out how to merge this here

**Comment by aschmiedeke** [comment]
Hey @mgsantamaria I am not sure if I am seeing your suggested changes. Did commit your solutions work for you?

**Comment by jdhenshaw** [comment]
sacrificing a bit of sense at high-v to gain sense at Sgr B2-v - think these will be weeded out in S3...image

image

sneaky broad comp ... image

image

image

image

image

image

image

image

image

image

image

image

image

image

**Comment by aschmiedeke** [comment]
@jdhenshaw: Spectra look good to me.

- 17: that's a lot of components, but if you think scouse will be able to weed them out, that's fine with me
- 18: definitely a sneaky one
- 32, 47, 50, 60, 66, 70, 78, 84, 148: looks good, ok
- 74: definitely better
- 102: I like that one
- 150: I am assuming the tiny component with the large errors will be weeded out as well? Or maybe we can get rid of that weak component? (See screenshot)

Screenshot 2022-10-13 at 09 22 37

**Review by jdhenshaw — APPROVED** [review]
review complete

**Pull request merged**
