### PR TITLE
S1.23.scousepy

### PR DESCRIPTION
**Pull request by DylanPare**
Initial fitting #24

### CODE REVIEW

**Comment by aschmiedeke** [comment]
When I follow our standard procedure for reviewing files, I get stuck pull from Dylan's repository. Here's the error message I get:

image

@DylanPare , @jdhenshaw : Any idea on what I could try?

**Comment by aschmiedeke** [comment]
Alright, after Adam's suggestion to use git pull -rebase, I managed to pull this. 

Fits look good, just tweaks of adding a component or two. Had been wondering after a couple if I had messed something up with the rebase. Am still unsure.

Before: 
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before: Not sure what to do with that one. I tried a few things, but I always either get a broad component or a not so good fit. Left it the way you had it.
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

**Comment by DylanPare** [comment]
Hey @aschmiedeke. Very weird that you were having difficulty with this PR.... I'm not sure why that would have happened as I made my branches and pushed to remote in the same way. Your updated fits look good! I tried improving the model fit to spectrum 60 and can't really improve on it. I would say that this branch is ready to be approved if you are satisfied with it.

**Comment by aschmiedeke** [comment]
Hey Dylan, yeah I don't know why either. But it looks like everything is ok now. If you're happy with the fitting results then that sounds good to me as well and we can go ahead with the merging :)

**Comment by jdhenshaw** [comment]
There is an issue with this PR that neither @aschmiedeke nor I can figure out. Closing and refitting

**Pull request closed without merging**
