### PR TITLE
S1.20.scousepy

### PR DESCRIPTION
**Pull request by aschmiedeke**
Refitting completed. #21 

Spectra look mostly ok.

Baseline deviates from 0 for a number of spectra (14, 15, 74, 75, 82, 83, 131-134)
Baseline deviates significantly from 0 for three spectra (16-18)

### CODE REVIEW

**Review by jdhenshaw — DISMISSED** [review]
Beginning review process

**Comment by jdhenshaw** [comment]
image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

**Comment by aschmiedeke** [comment]
Hey Jonny,

Spectra 7, 10, 11, 19, 30, 38, 42, 56, 75, 88, 112, 113, 127: I agree with your changes, I am starting to suspect that I am using a different pyspeckit version causing differences in achievable fitting solutions. (have to look into that).

Spectrum 15: Maybe let's try to get the small speak on the right of the main line as well? 
Spectrum 50: Maybe we can try a hybrid solution? 2 components for each line.
Spectrum 110: Maybe we can try a hybrid solution here as well? 2 components for each line.
Spectrum 138: Could we get the main line with 2 components? It does not look like a single component line to me.

**Comment by jdhenshaw** [comment]
15 - baseline issue meaning I can't catch the small peak at higher v
50 - done
110 - done 
138 - done

image

image

image

**Review by jdhenshaw — APPROVED** [review]
review complete

**Pull request merged**
