### PR TITLE
S1.15.scousepy

### PR DESCRIPTION
**Pull request by aschmiedeke**
#16

### CODE REVIEW

**Comment by jdhenshaw** [comment]
forgot the before pic, but this was a 2 comp fit image

image

image

image

image

image

sneaky broad... image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

**Comment by jdhenshaw** [comment]
There was a lot here - i think largely due to bad baselines? its fine though overall, just tweaks

**Comment by aschmiedeke** [comment]
Hey Jonny, thank you for going through this batch. It could have been baseline, or what I was thinking my scousepy version (I had been using an older version prior to our meeting in Heidelberg in early September) and the manual fitting did not work well for me at all. 

All spectra now look good to me! Thank you for going through all of them (and redoing so many manually).

**Review by jdhenshaw — APPROVED** [review]
review complete

**Pull request merged**
