### PR TITLE
S1.22.scousepy

### PR DESCRIPTION
**Pull request by aschmiedeke**
Refitting completed. #23

Spectra look mostly good.

Some showed negatives on either side of strong emission peaks (49-52)
Two spectra required a high SNR (121 needed SNR=20 and 127 needed SNR=24)
I can provide screenshots if needed, but there was nothing really weird/unusual/surprising.

### CODE REVIEW

**Review by jdhenshaw — DISMISSED** [review]
fitting complete

**Review by jdhenshaw — COMMENTED** [review]
some examples of modifications to the fitting:

image

image

image

image

image

image

In general the fits are good. However, there is a tendency for ScousePy to want to default to broad components towards the blue shifted end. Mostly this is stuff that is "in the weeds", i.e. very close to the noise. There are cases where multiple components can be fit. Others, ScousePy just wants to fit a big broad thing. Given that: 1. this is ambiguous (could be single broad thing or multiple components); 2. This is not the main gas associated with Sgr B2; I am opting to fit where I can, and ignore them at other times. In general, in my experience, it is better to not fit a component if you get a fit that isn't quite right/physical/ambiguous and/or if you *can* get a reasonable fit, one that may potentially even improve the fits to the main group of components (in this case ~70km/s) then go for it.

**Comment by aschmiedeke** [comment]
Hey Jonny, I looked through your fits:

- spectra 13, 18, 22, 41: I agree with your fits, they definitely are better.

- spectra 40 and 43: I would suggest a hybrid fit, where we dump the two weak/broad components on the left hand side but keep two components for the main line, see the screenshots below. What do you think? 

image (4)

image (5)

**Comment by jdhenshaw** [comment]
> Hey Jonny, I looked through your fits:
> 
> * spectra 13, 18, 22, 41: I agree with your fits, they definitely are better.
> * spectra 40 and 43: I would suggest a hybrid fit, where we dump the two weak/broad components on the left hand side but keep two components for the main line, see the screenshots below. What do you think?
> 
> image (4)
> 
> image (5)

Yep ok, I can do this

**Pull request merged**
