### PR TITLE
S1.11.scousepy

### PR DESCRIPTION
**Pull request by aschmiedeke**
Refitting completed. #12 
Spectra look good.

Just a few spectra with negatives on either side of strong emission peaks (1-3, 23, 40, 44-48, 62-64, 100-102, 106-108, 124-126, 129, 150).

### CODE REVIEW

**Comment by DylanPare** [comment]
Overall the spectra look good! A few spectra I made some modification to, however, which I mainly did using the manual fitting. Let me know what you think of these new fits:

**Comment by DylanPare** [comment]
Spectrum 33, original then new:
33_11_old
33_11_new

**Comment by DylanPare** [comment]
Spectrum 83, original then new:
83_11_old
83_11_new

**Comment by DylanPare** [comment]
Spectrum 84, original and new:
84_11_old
84_11_new

**Comment by DylanPare** [comment]
Spectrum 143, original and new:
143_11_old
143_11_new

**Comment by DylanPare** [comment]
Spectrum 145, original and new:
145_11_old
145_11_new

**Comment by mgsantamaria** [comment]
> Spectrum 143, original and new: 143_11_old 143_11_new

@DylanPare and @aschmiedeke in spectrum 143, I would suggest to find a better fit, that excludes the broad component that appears both in the original and in the new fit. And in the new, maybe the fainter component, with a linewidth ~ 5 +- 8 km/s. 


Also, in spectrum 84, in the new fit, I would exclude the component at v~87.7 km/s with a linewidth ~10+-7 km/s.

**Comment by aschmiedeke** [comment]
Hey @DylanPare  and @mgsantamaria, I had a look at the spectra. First of all, I did have a lot of trouble getting the fitting solutions you suggested. 

Summary: In total 7 spectra needed work; of those 4 still need some work in my opinion.

- **spec 3, 83, 145**: I agree with your solution, and I could reproduce it. I am posting the screenshots below, so that you can see which solution has been committed.
    - spec 3: Screenshot 2022-08-18 at 12 51 52_3-revised
    - spec 83: Screenshot 2022-08-18 at 13 05 51_83-revised
    - spec 145: Screenshot 2022-08-18 at 14 21 17_145-revised

    
- **spec 33**: Seeing your solution, I was thinking if it might be even better using 5 components (basically decomposing the wide component into two gaussians), but I couldn't get that to work. I could reproduce your suggestion though
Screenshot 2022-08-18 at 13 05 08_33-revised

- **spec 84**: I think 12 components are too many. I tried to get a better fit, but I wasn't able. Whatever else I tried, I always ended up getting an extremely wide component (>100 km/s).
Screenshot 2022-08-18 at 14 15 57_84-revised

- **spec 132**: I agree with your solution, but I could not get it myself. 
    > Spectrum 132, your solution: 132_11_new

    my solution Screenshot 2022-08-18 at 14 18 41_132-revised

- **spec 143**: As Miriam has mentioned, I would also like to try to get rid of the wide component. But I could not get that to work.
Screenshot 2022-08-18 at 14 19 46_143-revised


Please let me know what you think.

**Comment by DylanPare** [comment]
Hey @aschmiedeke Sorry for the delay in following-up on this. It looks like the spectra are mostly in good shape for this one. I will take a crack at spectrum 143 to see if I can remove the broad component, but it sounds like that might not be possible. Regarding spectrum 84, the broad component might only be removed by fitting more components, but I'll try spend some time to try and remove the broad component for that spectrum as well.

**Comment by DylanPare** [comment]
So, I've tried to remove the broad components in spectra 84 and 143:

Spectrum 84:
s1_11_84_new1

Spectrum 143:
s1_11_143_new

I think spectrum 143 looks okay, I decided just to fit the central peak, as adding additional components brought out broad components. I wasn't able to remove the broad components in spectrum 84 either, unless I fit to only the central peak. The resulting component isn't as broad, but it doesn't fit to the spectrum very well. Perhaps for spectrum 84 we keep the multi-component fit even with the broad component? What do you think @aschmiedeke ?

**Comment by aschmiedeke** [comment]
Hey Dylan, spectrum 143 looks good to me now. For spectrum 84, I would do what you suggest. Let's keep the broad-ish component, but with that also the other components. Could you commit your solutions? I'd then take a quick look and we can finalize this chunk. :)

**Comment by DylanPare** [comment]
Hey @aschmiedeke, are we set with this chunk as well?

**Review by DylanPare — APPROVED** [review]
review complete

**Pull request merged**
